DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CW, 30)
basic.pause(2000)
DFRobotMaqueenPlus.mototStop(Motors.ALL)
basic.pause(500)
DFRobotMaqueenPlus.mototRun(Motors.ALL, Dir.CCW, 30)
basic.pause(2000)
DFRobotMaqueenPlus.mototStop(Motors.ALL)
